[package]
name 	= "engineers_incubator_site"
version = "0.1.1"
edition = "2021"

[dependencies]
actix-files = "0.6"
actix-web 	= { version = "4.11", features = ["rustls"] }
tokio       = {	version = "1", features = ["full"] }
openssl		= { version = "0.10", features = ["vendored"] }
